apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app odoo
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/samipsolutions/odoo
      tag: "16.0@sha256:891573b93d76b75c110d70c276ba8ce8d7d0bc1e3564562213c87f62c047f993"
      pullPolicy: Always
    service:
      main:
        ports:
          http:
            port: 8069
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress-cf.${SECRET_DOMAIN}"
        hosts:
          - host: &host "erp.samipsolutions.fi"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    envFrom:
      - secretRef:
          name: odoo-secrets
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingCLaim: odoo-config-v1
        mountPath: /var/lib/odoo
      etc-config-file:
        enabled: true
        type: configMap
        name: odoo-configmap
        mountPath: /etc/odoo/odoo.conf
        subPath: odoo.conf
        readOnly: true
      extra-addons:
        enabled: true
        existingClaim: odoo-addons-v1
        mountPath: /mnt/extra-addons
