apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app odoo
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/samipsolutions/odoo
      tag: 16.0
    service:
      main:
        ports:
          http:
            port: 8069
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "erp.samipsolutions.fi"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    envFrom:
      - secretRef:
          name: odoo-secrets
    persistence:
      config:
        enabled: true
        existingCLaim: odoo-config-v1
        mountPath: /var/lib/odoo
