apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./pvc.yaml
  - ./pvc-addons.yaml
  - ./external-secret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: odoo-configmap
    files:
      - ./config/odoo.conf
generatorOptions:
  disableNameSuffixHash: true
