apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs
