apiVersion: v1
kind: Secret
metadata:
    name: odoo-secrets
    namespace: default
stringData:
    HOST: ENC[AES256_GCM,data:Xw635gnWdu9vSq0XYJqi7o3QYnlmmBfP8RsiXo8ctkzsPy71cD1AKJZuydRHVw==,iv:TOBn9yLrOZWML/GGeL0iMDaoDWN70Qrv2xjV26gxKmA=,tag:XYxiuz2Szcyqli5zaHVGcg==,type:str]
    PORT: ENC[AES256_GCM,data:0pxIpg==,iv:mAiFUeQXu1Mgk42Oopv8J1GxMA+NE4ULuRu5QkyoNDI=,tag:IqR/afXJExoPBe6D/iGaug==,type:str]
    USER: ENC[AES256_GCM,data:oC7fzQ==,iv:1SVpReQfjI/2d/coU3Zvsi80KmluAAsbjpvHi1kT/pg=,tag:Q533Zn37R3sHvme5LJKUOw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:AkbR33Oj5o5sMOl62MlfeKw9O8IDRuXWtWS6PFv7,iv:GNZKOapGUayaH6/7lVipqQGj4m1W41/0eZj3/UgtiB0=,tag:G1E6vxB2CltRHU1Cv4QU5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWnVPUkN5ck1LeStKbVZn
            RlNsUE1seVVHNTlMdis2Y2QvNVN3dGgxLzFRCmtOSnIxRzZxRDMxVmZlbitrODZT
            d0V6a3N5YnpKNlNWQWkrTGRiU0pWcEkKLS0tIGZtdE1yYUFOTU05U0VtSlRqUUlO
            NmN6UGk2Uy9ObGNlRkRzdURCdUFUWEEKWiBIRNMeKmuTxwk64jYUZa+aGQOQYUkw
            Kj7sSkLtAR8LwaQ/CQRzbUsyx/OgnT0nZ2HlcgduliBCo7a17gcitQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T03:57:30Z"
    mac: ENC[AES256_GCM,data:NlwFwx/pPsowq4F6fTpEuHMsTr5hVFOoVnXG1+utNH2LzhLFzFuIk3awt14oobdZ+CBY6glg3i+Wna2pUUGh6BM2LPkoMJCWMO7qni4JPdjj9tuagAFOhY+/phUCf/vCHNhoXTX1Y0TZlfVnOK/OQd1p+N1k9XLYjr4IDUXm9lU=,iv:uQgp2J7RyXq16ssrQoA2u7gMWH6+rZC68BrDkkV5w8M=,tag:AnB+R7/vn7hDMHhsg6uwpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
