---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ci-woodpecker-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: ci-woodpecker-server
  path: ./kubernetes/apps/ci/woodpecker/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: woodpecker-agent
      namespace: ci
  interval: 30m
  retryInterval: 1m
  timeout: 3m
