apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forego
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: forego
  target:
    name: forego-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FOREGO_ADMIN_PASSWORD: "{{ .FOREGO_ADMIN_PASSWORD }}"
        FOREGO_ADMIN_EMAIL: "{{ .FOREGO_ADMIN_EMAIL }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_USERNAME: &dbUser "{{ .POSTGRES_USERNAME }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: forgejo
        INIT_POSTGRES_HOST: postgres-default-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: .*
