---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: forego
  namespace: dev
spec:
  interval: 15m
  chart:
    spec:
      chart: forgejo
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: forego-helm
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    gitea:
      admin:
        username: kryptonian
      config:
        APP_NAME: 'Forego'

        repository:
          DEFAULT_BRANCH: main
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
          REVERSE_PROXY_LIMIT: 1
          REVERSE_PROXY_TRUSTED_PROXIES: 10.50.0.0/24
        server:
          SSH_PORT: 222
        service:
          DISABLE_REGISTRATION: true
          # REQUIRE_SIGNIN_VIEW: true
        cron:
          ENABLED: true
        database:
          DB_TYPE: postgres
          HOST: postgres-default-rw.database.svc.cluster.local:5432
          NAME: forgejo
          SCHEMA: public
          SSL_MODE: disable
        mailer:
          ENABLED: true
          PROTOCOL: smtp
          SMTP_ADDR: smtp-relay.default
          SMTP_PORT: 2525
          FROM: "Forgejo <forgejo@${SECRET_DOMAIN}>"
        cache:
          ADAPTER: redis
          HOST: redis://redis.database.svc.cluster.local:6379/11
        queue:
          TYPE: redis
          CONN_STR: redis://redis.database.svc.cluster.local:6379/10
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://redis.database.svc.cluster.local:6379/12


        indexer:
          REPO_INDEXER_ENABLED: true
          REPO_INDEXER_REPO_TYPES: sources
    strategy:
      type: 'Recreate'
    image:
      registry: "codeberg.org"
      repository: forgejo/forgejo
      tag: "1.21.8-0"
      rootless: true

    podSecurityContext:
      fsGroup: 1000

    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false

    service:
      ssh:
        hostPort: 222
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
      hosts:
        - host: &host "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
           - *host

    postgresql:
      enabled: false
    memcached:
      enabled: false

    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1Gi

    persistence:
      enabled: true
      claimName: data-forego-forgejo-0
      size: 20Gi
      accessModes:
        - ReadWriteOnce

  valuesFrom:
    - targetPath: gitea.admin.email
      kind: Secret
      name: forego-secret
      valuesKey: FOREGO_ADMIN_EMAIL
    - targetPath: gitea.admin.password
      kind: Secret
      name: forego-secret
      valuesKey: FOREGO_ADMIN_PASSWORD
    - targetPath: gitea.config.database.PASSWD
      kind: Secret
      name: forego-secret
      valuesKey: POSTGRES_PASSWORD
    - targetPath: gitea.config.database.USER
      kind: Secret
      name: forego-secret
      valuesKey: POSTGRES_USERNAME
