apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: woodpecker
  target:
    name: woodpecker
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        WOODPECKER_GITEA_URL: "{{ .WOODPECKER_GITEA_URL }}"
        WOODPECKER_GITEA_CLIENT: "{{ .WOODPECKER_GITEA_CLIENT }}"
        WOODPECKER_GITEA_SECRET: "{{ .WOODPECKER_GITEA_SECRET }}"
        WOODPECKER_AGENT_SECRET: "{{ .WOODPECKER_AGENT_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: .*
