apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: woodpecker
  target:
    name: woodpecker
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        WOODPECKER_GITEA_URL: "{{ .WOODPECKER_GITEA_URL }}"
        WOODPECKER_GITEA_CLIENT: "{{ .WOODPECKER_GITEA_CLIENT }}"
        WOODPECKER_GITEA_SECRET: "{{ .WOODPECKER_GITEA_SECRET }}"
        WOODPECKER_AGENT_SECRET: "{{ .WOODPECKER_AGENT_SECRET }}"
        WOODPECKER_DATABASE_DATASOURCE: "postgres://{{ .WOODPECKER_POSTGRES_USER }}:{{ .WOODPECKER_POSTGRES_PASS }}@postgres-default-rw.database.svc.cluster.local:5432/woodpecker?sslmode=disable"
  dataFrom:
    - find:
        name:
          regexp: .*
