---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app woodpecker
  namespace: ci
spec:
  interval: 15m
  chart:
    spec:
      chart: woodpecker
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    server:
      enabled: true
      image:
        registry: docker.io
        repository: woodpeckerci/woodpecker-server
        pullPolicy: IfNotPresent
        tag: ""
      env:
        WOODPECKER_ADMIN: "kryptonian,admin"
        WOODPECKER_HOST: "https://ci.${SECRET_DOMAIN}"
        WOODPECKER_GITHUB: false
        WOODPECKER_GITEA: true
        WOODPECKER_GITEA_SKIP_VERIFY: "true"
        WOODPECKER_OPEN: false

      extraSecretNamesForEnvFrom:
        - woodpecker

      persistentVolume:
        enabled: true
        size: 10Gi
        mountPath: "/var/lib/woodpecker"

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ingress-cf.${SECRET_DOMAIN}
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:drone
          hajimari.io/appName: Woodpecker
        hosts:
          - host: &host "ci.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

        podAnnotations:
          secret.reloader.stakater.com/reload: *app

    agent:
     enabled: true
     replicaCount: 1

     env:
       WOODPECKER_SERVER: "woodpecker-server:9000"
       WOODPECKER_BACKEND: kubernetes
       WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker
       WOODPECKER_BACKEND_K8S_STORAGE_CLASS: ""
       WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 10G
       WOODPECKER_BACKEND_K8S_STORAGE_RWX: false

     extraSecretNamesForEnvFrom:
       - woodpecker

     podAnnotations:
       secret.reloader.stakater.com/reload: *app


