---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app woodpecker
  namespace: ci
spec:
  interval: 15m
  chart:
    spec:
      chart: woodpecker-server
      version: 0.15.6
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:
      WOODPECKER_ADMIN: "kryptonian,admin"
      WOODPECKER_HOST: "https://ci.${SECRET_DOMAIN}"
      WOODPECKER_GITHUB: false
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_SKIP_VERIFY: "true"
      WOODPECKER_OPEN: false

    extraSecretNamesForEnvFrom:
      - *app

    persistentVolume:
      enabled: true
      size: 5Gi
      mountPath: "/var/lib/woodpecker"

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:drone
        hajimari.io/appName: Woodpecker
      hosts:
        - host: &host "ci.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

      podAnnotations:
        secret.reloader.stakater.com/reload: *app
