ansible_become_pass: ENC[AES256_GCM,data:LgLIyw==,iv:u/66kg6LXvuYrgSSLJTtnnAF5rtuHeKjyJ8Y/OsEqR4=,tag:tazX6Vkl2HWrocGIhAk8wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUWdUOTgrT0IvMnJtWThw
            L21iR3JIY2FmLzZucWx1TjJybmkwNkpYZTIwCk9HWDh1K3ViRkF4UUJtdjRDakh5
            L25VMGxoS1p0OW1OK3NWWFIva0ZIelEKLS0tIDhiRFVJWDdhR1h3WVhSd1BCUGJv
            MjNjaUxlK3dDRVlTNi9mZ3U3b0VvRjgKOuWsEQOzjE0RRDPoLO7wJzcdeaZPlDKf
            e13OK7pV49cpXdHdMlfv7BXI2HMZ07PweTUlt62Tqoi6WKMzKliFGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-13T10:01:13Z"
    mac: ENC[AES256_GCM,data:gUQ0jvkv+S+4abr22FwlzDykUbhSLKub/Ch7MZiEd6EpmN4wgQGjcfnrxVBYTRAD0TNr+UY2tQTK8O+rFUFsubdhEhoTlgvLke8xD+xYcQs4VL+/lOXq7Uo+soW9ympbGmiUPr5LhoHjNsCTn1mFBTxUveLWq+Vz7Joq38zFl9M=,iv:2ukONt/Y9s4fORmz4uvZFt85ksAnLKl25+LmRY2C1WI=,tag:3MHetgZVQtRM6XY49r1nLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
