apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres
        ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "{{ .ZITADEL__POSTGRES_USER }}"
        ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "{{ .ZITADEL__POSTGRES_PASSWORD }}"
        # Postgres Init
        ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "{{ .postgres-username }}"
        ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "{{ .postgres-password }}"
        # Masterkey
        masterkey: "{{ .ZITADEL_MASTERKEY }}"
  dataFrom:
    - extract:
        key: zitadel
    - extract:
        key: cloudnative-pg
