---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app woodpecker-agent
  namespace: ci
spec:
  interval: 15m
  chart:
    spec:
      chart: woodpecker-agent
      version: 0.15.6
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    env:
      WOODPECKER_SERVER: "woodpecker-woodpecker-server.ci.svc.cluster.local:9000"


    extraSecretNamesForEnvFrom:
      - woodpecker

    podAnnotations:
      secret.reloader.stakater.com/reload: *app
