---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_default_ipv4.address  }},{{ ansible_default_ipv6.address }}"
  node-external-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ kube_vip_addr }}"
    - "{{ ansible_default_ipv4.address }}"
    - "{{ ansible_default_ipv6.address }}"
    - "{{ ansible_host }}"
  docker: false
  flannel-backend: "vxlan"
  disable:
    - coredns                         # Disable coredns                 - replaced with Coredns Helm Chart
    - local-storage                   # Disable local-path-provisioner  - installed with Flux
    - metrics-server                  # Disable metrics-server          - installed with Flux
    - traefik                         # Disable traefik                 - replaced with ingress-nginx and installed with Flux
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  cluster-cidr: "{{ cluster_cidr }},{{ cluster_cidr_v6 }}"
  service-cidr: "{{ service_cidr }},{{ service_cidr_v6 }}"
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-scheduler with kube-prometheus-stack
  kube-apiserver-arg:
    - "anonymous-auth=true"           # Required for HAProxy health-checks
