apiVersion: v1
kind: Secret
metadata:
    name: exteranldns-kapsi-secrets
    namespace: networking
stringData:
    bind_rndc_algorithm: ENC[AES256_GCM,data:btUoy2hiZtSciaY=,iv:F2G3RuM6mz7rEZrJlEhygInZmMs4kLVvaaEoxdn03Z4=,tag:d0BLSMyS8eDJWv+0B+vIKg==,type:str]
    bind_rndc_secret: ENC[AES256_GCM,data:YInvhuleBRn70LYltscwbgwFzJplnnUhwCYCG2l97dYNoTuTCKn/ZPNZBHo=,iv:d8kztsflaJ0jOzpDiFjgzInwOpBXXT1kolNCXdpXHEU=,tag:vWZlAdPIgISHp/o3Z7tgNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQUtzWGk5QXlrT1YyeENK
            ckdlaTMyNVp1V0tUYWw3azl3VytRcGYvcVJNClRJZHdudWdFMDQ3ZWozOUlmMzhX
            Q2lIbzZteEI4amFuMk0wT0I0dnN6dUUKLS0tIE14Z2JBbTY2emZoN2dMRjluQ0Vs
            YXJTNzAxVHB0NmZMa25nZUN1UGJicU0KuTWl/JtelJacpW17k2Z7bbaTCJTvKyCa
            RJV1JyIaGDK719i/GbI6Z0xY1Zbb7YoBwT5gibBFt8kD9xJOqoEpHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T17:41:53Z"
    mac: ENC[AES256_GCM,data:tkIjzOgJRm7VyZSV91g8KQbQASLfCh4RFLoJG50zDAXitpNKdPAXaFcvQiOp51iqI8Wp4QBUWJTeI2qTvehXGl8vRXkszcp/Jrv3SFm0ZCAXFZhWfULOxaY3Sku6zNwr7/GEyEqW3IXEYYSGd+gDBBRUbdCUQe6j2+fqs6gdaV4=,iv:R5j235ZRX7stfDuqDd9tBFV88iUy0hlWhb6LD+/LZpQ=,tag:cl4d35K7gSQO8rhKdhHpFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
