apiVersion: v1
kind: Secret
metadata:
    name: externaldns-kapsi-secrets
    namespace: networking
stringData:
    bind_rndc_algorithm: ENC[AES256_GCM,data:VD8SwP46YFo5pxo=,iv:QVMliV21jKi+02uzIeU33gHtmRtlbIibDa78/9jN/Ms=,tag:uKCRQvc4DQozjdfjQCmf9A==,type:str]
    bind_rndc_secret: ENC[AES256_GCM,data:2sSitLONjubYRIDvAEKBlEVZy2rA5zYJ/tChpQAsDPuqvleIllg6axTIAGU=,iv:bkZk9QDknc9g5rVjE369tIzVfueqqfmMPj4zgdcOJLo=,tag:GtfsgFGtm1UaCzyoJ5wWxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0FqSi8wVTZDaUxSSE04
            T3hMdWRhdGZHZ2NlNzh6ejVjblR5eExDQ1ZzCkpXWjVXYVowdU1KTFhuTjR0a2Fr
            cEpHSkFyemo1VXZubXhwcXY4YVBtT0UKLS0tIHdRS2NhUHI1TkZCUkE5SDJTRGlK
            ZU5udkZuSGJQVlFZTlExS3U2UUdMZ2cKK/uVJxU9h2CF3QqwzWzgYe+CPGHBH1Mb
            Z9NE8jkg8SpzDs3NzHEq/N3FEXow7JMUj6rg+OtlITlbH26ummaw1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T17:50:52Z"
    mac: ENC[AES256_GCM,data:y13NI4t49Gl24HYFmPpjFbKy68dHXDKpWPNaVTuJ/uFVOu/TxIIw2q/AMJ40HZZRDj23rwKsBAFDLJ+qCdy2RZoU3zgWwHKNbAdVriuHQBesZ9ukgeAcKWdMyLqwTAUK6qOV6DOI2pDnQVnY09cK1izf/dSFOTF3zbVIA5F5CSA=,iv:hEptSNNsmgbavAwT+JkFeJ3eXE0/xtzlv82Np2d97f0=,tag:f8XBTAFvFUR8yHc+NbBEvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
