apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-relay
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: smtp-relay
  target:
    name: smtp-relay-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SMTP_DOMAIN: "{{ .SMTP_DOMAIN }}"
        SMTP_SERVER: "{{ .SMTP_SERVER }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: .*
