---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-validation-webhook
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: snapshot-validation-webhook
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
