---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piped
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: piped
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    frontend:
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/docker/1337kavin/piped-frontend
        tag: latest
        pullPolicy: Always

      env:
        BACKEND_HOSTNAME: api.piped.fi

    backend:
      initContainers:
        01-init-db:
          image: ghcr.io/onedr0p/postgres-init:14.9
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: &secret piped-db-creds
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/docker/1337kavin/piped
        tag: latest
        pullPolicy: Always

      config:
        PORT: 8080
        NUM_WORKERS: 2
        PROXY_PART: https://proxy.piped.fi
        #DISABLE_REGISTRATION: true
        database:
          connection_url: jdbc:postgresql://postgres-default-rw.database.svc.cluster.local/piped
          secret: *secret

    ytproxy:
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/docker/1337kavin/piped-proxy
        tag: latest
        pullPolicy: Always

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
            secretName: piped-production-tls

      backend:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &api_host api.piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *api_host
            secretName: piped-production-tls


      ytproxy:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &proxy proxy.piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *proxy
            secretName: piped-production-tls
    postgresql:
      enabled: false
