---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: piped
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: piped
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    frontend:
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/docker/1337kavin/piped-frontend
        tag: latest
        pullPolicy: Always

      env:
        BACKEND_HOSTNAME: api.piped.fi

    backend:
      podAnnotations:
        configmap.reloader.stakater.com/reload: "piped-backend-config"
      initContainers:
        01-init-db:
          image: ghcr.io/onedr0p/postgres-init:14.10
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: &secret piped-db-creds
      additionalContainers:
        gluetun:
          image: registry.samipsolutions.fi/docker/qmcgaw/gluetun:v3.38.0
          imagePullPolicy: IfNotPresent
          env:
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_SERVICE_PROVIDER
              value: airvpn
            - name: VPN_INTERFACE
              value: wg0
            - name: FIREWALL
              value: "off"
            - name: DOT
              value: "off"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: 51820,55633
            - name: SERVER_REGIONS
              value: Europe
            - NAME: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS
              value: ":8888"
            - name: HTTPPROXY_STEALTH
              value: "on"
          envFrom:
            - secretRef:
                name: piped-vpnconfig
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/library/piped
        tag: "1.9"
        pullPolicy: Always

      config:
        PORT: 8080
        HTTP_WORKERS: 4
        PROXY_PART: https://proxy.piped.fi
        HTTP_PROXY: 127.0.0.1:8888
        #DISABLE_REGISTRATION: true
        database:
          connection_url: jdbc:postgresql://postgres-default-rw.database.svc.cluster.local/piped
          secret:
           name: *secret
           username: DB_USERNAME
           password: DB_PASSWORD

    ytproxy:
      enabled: false
      image:
        # Pull-though cache
        repository: registry.samipsolutions.fi/docker/1337kavin/piped-proxy
        tag: latest@sha256:6bcaad44c5c7112625e21792d49ed7afc364a5460f266d80fe6c65c001bddc03
        pullPolicy: Always
      env:
        RUST_BACKTRACE: 1

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
            secretName: piped-production-tls

      backend:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &api_host api.piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *api_host
            secretName: piped-production-tls


      ytproxy:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &proxy proxy.piped.fi
            paths:
              - path: "/"
        tls:
          - hosts:
              - *proxy
            secretName: piped-production-tls
    postgresql:
      enabled: false
