apiVersion: v1
kind: Secret
metadata:
    name: piped-db-creds
    namespace: default
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:4mpYWPQ=,iv:Tgf2MLo90NyM7TZh6XmQkO7cqCDxa39JOuZJVhtJO0c=,tag:n29U38EGLmjNL+l/3HvCdw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:tD4b3A5C4HMr06E0FkG7aEoOLG4rZX4oSjbzJtZiqV7bbiiWBwAyRLUAgG7LxA==,iv:ZVCKqWUuwPhCoURt8awbcLMnypsUa6D8GWHc61OEsKc=,tag:gGXTIjTrbyMUpiZeUK2bLA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:awQpfZc=,iv:iCwo0rd/cFvbXvH7uwo6Tc+dp4cgAaVpTekIuGfWKGI=,tag:f8fWKB9OhKiprY8D0aFIsw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:7EdQe/i2YJQf46k9Qfx/9cl5zS64+Q5cAAVNdr5A21Mx641Cbf/Zsg==,iv:Xse3W3QLXd8amobNP6SMeAerugoC0EQsR9pd/wt/zOw=,tag:/Dy+r2LwzSKUh/Ygt6SnTw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:rUz4NxI=,iv:ayCMuhduu5lsrGOrWgg/dWp9pw6rqKjT5m454hBAH80=,tag:K10Icw8s+YwuTy2TGMhbew==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Cu8rAZn2YB955M2POnthYscUWCfrYBpSG4iorJ1N4u/9raQdXc7DfSWJ2pToYw==,iv:YAWQukOjxIKz6Vnld009xMmZgBc2LLwYW9PloXsELy0=,tag:UOBt83wpbV7FN7VzR3PmIA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:G66VhSc=,iv:VWF5Eq8GvEANemez9Z5CCrxd3v6tiEoZ9Pi8JdZoa1Q=,tag:lvBXyIXhiLZUNhiMC7AngA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LhrHsu6mSyknRZKDApVyLTS4xh1P/0ezs2x0ebU8nRtA/k5fwbWHJA==,iv:FfZRvXYWiKa0znz7zDInkFmsf2HsCq3hG+/fOfP6eNY=,tag:2bfiRkhzYxmpm0cuqupjfg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:L/iuA3HzZWQMBev6LA7GRRpQU2f1DaE0mGkdNbXuYxGUgWDeF4hf4ZL45rrG5wJc4zgvOmuPxwpsU7NnFqqhpw==,iv:CeZgRK0IF+OHGQ0FUWJh3/xk/pb2sU6CzQ52Q42dAcI=,tag:JUkiBTmVvDPRTg+48htUBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTTVxdEY4ZjJ6dXNnWmh2
            TmorMnBEdk9LekRYemtRbDdjeGx3c1FmV1RvCjRNRWJKRjA4Ym55UjBWQ3hvVC93
            TFc4MFFlZDlJTUlYM0h5OFpUbXV6NTQKLS0tIEI0Nm1Db1NXSGFXYlN1RlJmYi8w
            WVJROFFSZ3dJcGRwVEpmL2dkMWFKNUEKt44lUkWIEV51LZhJ3IRk07z+AvEfbNzd
            Iij52rx279KOxQuw3o9xaMVnn18ampoovZheMEuWNshORF26kS4DQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T17:56:21Z"
    mac: ENC[AES256_GCM,data:yWNHZMv3ce5syGf8s4GrNWFUaPxtaFQPDS/Rb3kwEhAbWM4GN0wWwsxrGxm9S5H6uszpkqIWSM+zvF0raAVgc20JNNtITDqD5WDQc0uSGwOwd07Q+OGsisvSBEVIDXhTiireUc6Mjphn83Hi1HRNx7JlctVR+wSddAxrf3gM5RI=,iv:GEvuBw2wHd/xkpcLpop+9pqRZ4bxhEFG9ksMadNjtXo=,tag:v1Kqkmi2NHh3sHPS5p7o7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
