unlock:
  desc: Unlock a Restic repository for an application
  summary: |
    Args:
      ns: Namespace the PVC is in (default: default)
      app: Application to unlock (required)
  cmds:
    - envsubst < <(cat {{.VOLSYNC_TEMPLATES_DIR}}/unlock.tmpl.yaml) | kubectl apply -f -
    - bash {{.VOLSYNC_SCRIPTS_DIR}}/wait-for-job.sh {{.job}} {{.ns}} {{.cluster}}
    - kubectl -n {{.ns}} wait job/{{.job}} --for condition=complete --timeout=1m
    - kubectl -n {{.ns}} logs job/{{.job}} --container r2
    - kubectl -n {{.ns}} delete job {{.job}}
  requires:
    vars: ["app"]
  vars:
    ns: '{{.ns | default "default"}}'
    job: volsync-unlock-{{.app}}
  preconditions:
    - test -f {{.VOLSYNC_SCRIPTS_DIR}}/wait-for-job.sh
    - test -f {{.VOLSYNC_TEMPLATES_DIR}}/unlock.tmpl.yaml
  silent: true
