apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    PGADMIN_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:NSapKJF5X8tDDzoDQm7rTST2JlOLexS7wC5h,iv:kCD5splMQEN+vi17XR0qKeEwZqQRfAH6dgGfVBYBJGE=,tag:TNhq7x0P3BRPYTC7dpPQYA==,type:str]
    PGADMIN_OAUTH_SECRET: ENC[AES256_GCM,data:BwAxx9kDVe3sgsPiceTbRWdFC5DrH6xrNHZ8T1yvlv5u6cuWP289F2vXCOi/uY5LWdtypUWtzl6XLfjDJkGKhg==,iv:ooOhMDQatTz6ADVk3F7qDpNACTO4Q3AtofcDWmYUioo=,tag:BPntazwJ7WAo2ULATWIS7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3NhMTNzR0FtYnBQMUVy
            Z2lqdnd5c2lFN01QUWF1dk9wejVINnNCRWc4ClV6OGpMQWRLOU1sT1A3c0tKUWVo
            ZW9oZVZhU3B1VTN5VVZYbVc1c0VjQU0KLS0tIEhkTzEyNER4VzBuQTZWTEhkaDRX
            Zy9QU2Q0MmJSY2ZTemFNV05kWDRmV28KQVUv+qNbhOnYmv5FjupBw5+TAlffZuMY
            fEKfbaUkxPZyLSB5fs+djWGpBIwTS+10O5gdNrEaLpegeNfeXDqAGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T17:06:31Z"
    mac: ENC[AES256_GCM,data:878uYQ8Kx50NEYAns8YdSjBEnqtEgdGVroWyETIIqPvhP1EORkgBTdeLX/LPfdtttr+PdasljSSb7YOLFcEv+IEMYNpP8uKDXQ1zHugJzuOTD/MOTYrRyrzenRlXBRebaoq0tzkFRrAJDu0dfudJaIbwn73cCu2I4S1xLuT3Q8U=,iv:/Hgtau8/ec4M6wgQ7jplogVZ3ByyqeE3zIfa9OMwctY=,tag:hgRDkLPZNwqsBkfOVMRMCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
