---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-forego
  namespace: flux-system
spec:
  dependsOn:
    - name: system-doppler-secret
  path: ./kubernetes/apps/dev/forego/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: forego
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
