---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-forego
  namespace: flux-system
spec:
  targetNamespace: dev
  path: ./kubernetes/apps/dev/forego/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: forego
      VOLSYNC_CLAIM: forego-data
      VOLSYNC_CAPACITY: 20Gi
      APP_UID: "1000"
      APP_GID: "1000"
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            metadata:
              name: forego
      target:
        kind: Deployment
        name: forego-forgejo

