---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: dpage/pgadmin4
      tag: "7.6"

    controller:
      replicas: 1
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"
    strategy:
      type: Recreate

    envFrom:
      - secretRef:
          name: pgadmin-secret
    service:
      main:
        ports:
          http:
            port: 80

    persistence:
      config:
        enabled: true
        storageClass: zfs
        mountPath: "/var/lib/pgadmin"
        size: 1Gi
      local-config:
        enabled: true
        type: configMap
        name: pgadmin-local-config-configmap
        subPath: config_local.py
        mountPath: /pgadmin4/config_local.py
        readOnly: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: pgadmin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - pgadmin.${SECRET_DOMAIN}

    resources:
      requests:
        memory: 164M
      limits:
        memory: 236M
