---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: pgadmin-local-config-configmap
    files:
      - config_local.py
generatorOptions:
  disableNameSuffixHash: true
