apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: windmill
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: windmill
  target:
    name: windmill-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        WINDMILL_POSTGRES_URL: "postgres://windmill:{{ .POSTGRES_PASS }}@postgres-default-rw.database.svc.cluster.local/windmill?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: windmill
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: windmill
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: .*
