apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .postgres-password }}"
        username: "{{ .postgres-username }}"
        aws-access-key-id: "{{ .aws-access-key-id }}"
        aws-secret-access-key: "{{ .aws-secret-access-key }}"
  dataFrom:
    - extract:
        key: cloudnative-pg

