apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:z27Wi+A9nvw=,iv:D8FcUh3OUwvXikzf9KECGjvL/Wh/F4gnI7iy87sCKfU=,tag:am3oPj+hu9eYuiI0Xb5/wQ==,type:str]
    password: ENC[AES256_GCM,data:iQXfMf4RgPtKA0XIzFQ/bguybRcEcJblwBTLQOO6,iv:+jGbtoXghpvlQYzFMjqxjihxv6aTEeoYkhLky6RoOtY=,tag:SHeqd41TanhM/PPn4Umi3Q==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:tEh6LNAsyFdYBbNyCgNG3pbtsHg=,iv:0tXDE/cWPd83k2mUf84TSx+bQxUh151P9NZlHQlmWKc=,tag:hcqhhP0fJxKMJbcRBDXp8g==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:N/oUmH9zM3v7EBm2lVJN6t/HzpkbozTJ1VfvT2KEiiV0vhCCla5FdQ==,iv:AI0m2R/LtAag9ZVm3fx8Sa+gm9Bzjq10kXJpc8ET+nk=,tag:s988S7x/Eu3TVqO1blyYVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTHFOZFZ3YnpLRkRndXVP
            Q0NNZFMxdGZkbG1qM1V0RXJZamxKeG81UlZvCmEvcEI0RTBVS2ZMVjFRWng2eGtK
            dU9SVThsdkN6VVhWQ2ZFYURLQ1hROUEKLS0tIDViakVTbHRVVXJkek5FR1ZTcDYw
            dHloNmFoNWhaRUtCOThVOG9EZXQwSDQK2pl2Va+uM4z9afzsXOYfKwwPna1K5fW4
            ZnfI/tR1aQUoHGSesZ07WPHdmWRLF32dS+Gerf0mqwX5MUY95CtxBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T05:55:06Z"
    mac: ENC[AES256_GCM,data:LAaFXWdK2TrFvHC4wkVkSxIF7KbZIXb2/J12GdfApUNKwHIY65GJt+Q2ikh8VFfchB1vdyrM6XctvQkBlbAQ0Vx5u2lJS7mjfn5nEsbx85H+t6BTYURfFGrgGaWUwzRgBkFmKqEgSm/aIkWRQeu6lJj2rH3+PuscjaxhTqt56Hg=,iv:DcqDCkwOHpytEc79zXxcuR/N5jRBTV/PBmFgA0STsFA=,tag:1nftON5nYkqUi6G4dpPqjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
