---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: networking
spec:
  endpoints:
    - dnsName: "ingress-cf.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]
    - dnsName: "ingress-cf.${SECRET_DOMAIN_2}"
      recordType: CNAME
      targets: [ "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com" ]
